import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Product Project",
  authors: [{ name: "Hazim Bakar", url: "https://github.com/hazimba" }],
  creator: "Hazim Bakar",
  keywords: ["product", "project", "nextjs", "react"],
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/new-product.png", type: "image/png" },
      // { url: "/favicon.ico", type: "image/x-icon" },
    ],
    apple: "/new-product.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>{children}</body>
    </html>
  );
}
